/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './index.html'],
  theme: {
    extend: {
      // Every token from src/styles/globals.css under its own name, so a class
      // reads as the token does: `bg-bg-surface`, `text-text-primary`,
      // `border-border-subtle`, `text-accent`. The stylesheet stays the single
      // source of truth; src/__tests__/tailwindTokens.test.ts fails if this
      // list and the stylesheet drift apart — see plan E4.
      colors: {
        'bg-app': 'var(--bg-app)',
        'bg-surface': 'var(--bg-surface)',
        'bg-toolbar': 'var(--bg-toolbar)',
        'bg-filmstrip': 'var(--bg-filmstrip)',
        'bg-hover': 'var(--bg-hover)',
        'bg-selected': 'var(--bg-selected)',
        'bg-canvas': 'var(--bg-canvas)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        'border-focus': 'var(--border-focus)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-on-dark': 'var(--text-on-dark)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-dim': 'var(--accent-dim)',
        'accent-light': 'var(--accent-light)',
        live: 'var(--live)',
        'live-bg': 'var(--live-bg)',
        'live-border': 'var(--live-border)',
        'live-dim': 'var(--live-dim)',
        danger: 'var(--danger)',
        'danger-dim': 'var(--danger-dim)',
        white: 'var(--white)',
        black: 'var(--black)',
        'text-on-accent': 'var(--text-on-accent)',
        'projector-bg': 'var(--projector-bg)',
        'projector-text': 'var(--projector-text)',
        'danger-bright': 'var(--danger-bright)',
        'live-hover': 'var(--live-hover)',
        'live-outline': 'var(--live-outline)',
        dirty: 'var(--dirty)',
        'dirty-text': 'var(--dirty-text)',
        saved: 'var(--saved)',
        'thumb-bg': 'var(--thumb-bg)',
        'home-heading': 'var(--home-heading)',
        'on-dark-1': 'var(--on-dark-1)',
        'on-dark-2': 'var(--on-dark-2)',
        'on-dark-3': 'var(--on-dark-3)',
        'on-dark-4': 'var(--on-dark-4)',
        'on-dark-5': 'var(--on-dark-5)',
        'on-dark-6': 'var(--on-dark-6)',
        'on-dark-7': 'var(--on-dark-7)',
        'on-dark-8': 'var(--on-dark-8)',
        'on-dark-9': 'var(--on-dark-9)',
        'on-dark-10': 'var(--on-dark-10)',
        'on-dark-11': 'var(--on-dark-11)',
        'section-1': 'var(--section-1)',
        'section-2': 'var(--section-2)',
        'section-3': 'var(--section-3)',
        'section-4': 'var(--section-4)',
        'section-5': 'var(--section-5)',
      },
      // Gradient tokens are images, not colours: `bg-home-cta-gradient`.
      backgroundImage: {
        'home-cta-gradient': 'var(--home-cta-gradient)',
      },
    },
  },
  plugins: [],
};
